[package]
name = "ovoir"
type = "bin"
authors = [""]
compiler_version = ">=0.23.0"

[dependencies]
ecrecover = { tag = "v0.19.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
#noir_merkleroot = { tag = "v0.1.1", git = "https://github.com/tomoima525/noir-merkle-root" }